config/routes.rb
Wineapp::Application.routes.draw do
  
  resources :wineries do
    resources :wines
  end

  root :to => 'wineries#index'

  get "/wines" => 'wines#all'
  # Is there a way to do this through wines#index?

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  attr_accessible :description, :name, :winery_id
  validates :name, :presence => true 
  belongs_to :winery
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/winery.rb
class Winery < ActiveRecord::Base
  attr_accessible :location, :name
  validates :name, :presence => true
  has_many :wines, :dependent => :destroy
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  # GET /wineries
  # GET /wineries.json
  def index
    @wineries = Winery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wineries }
    end
  end

  # GET /wineries/1
  # GET /wineries/1.json
  def show
    @winery = Winery.find(params[:id])
    if request.path != winery_path(@winery)
      redirect_to @winery, status: :moved_permanently
    else
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @winery }
      end
    end
  end

  # GET /wineries/new
  # GET /wineries/new.json
  def new
    @winery = Winery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @winery }
    end
  end

  # GET /wineries/1/edit
  def edit
    @winery = Winery.find(params[:id])
  end

  # POST /wineries
  # POST /wineries.json
  def create
    @winery = Winery.new(params[:winery])

    respond_to do |format|
      if @winery.save
        format.html { redirect_to @winery, notice: 'Winery was successfully created.' }
        format.json { render json: @winery, status: :created, location: @winery }
      else
        format.html { render action: "new" }
        format.json { render json: @winery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wineries/1
  # PUT /wineries/1.json
  def update
    @winery = Winery.find(params[:id])

    respond_to do |format|
      if @winery.update_attributes(params[:winery])
        format.html { redirect_to @winery, notice: 'Winery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @winery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wineries/1
  # DELETE /wineries/1.json
  def destroy
    @winery = Winery.find(params[:id])
    @winery.destroy

    respond_to do |format|
      format.html { redirect_to wineries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  # GET /wines
  # GET /wines.json
  def index
    @winery = Winery.find(params[:winery_id])
    @wines = @winery.wines

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wines }
    end
  end

  def all
    @wines = Wine.all

    respond_to do |format|
      format.html # all.html.erb
      format.json { render json: @wines }
    end
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    @winery = Winery.find(params[:winery_id])
    @wine = @winery.wines.find(params[:id])

    respond_to do |format|
    format.html # show.html.erb
    format.json { render json: @wine }
    end
  end

  # GET /wines/new
  # GET /wines/new.json
  def new
    @winery = Winery.find(params[:winery_id])
    @wine =  @winery.wines.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wine }
    end
  end

  # GET /wines/1/edit
  def edit
    @winery = Winery.find(params[:winery_id])
    @wine = @winery.wines.find(params[:id])
  end

  # POST /wines
  # POST /wines.json
  def create
    @winery = Winery.find(params[:winery_id])
    @wine = @winery.wines.build(params[:wine])

    respond_to do |format|
      if @wine.save
        format.html { redirect_to [@wine.winery, @wine], notice: 'Wine was successfully created.' }
        format.json { render json: @wine, status: :created, :location => [@wine.winery, @wine] }
      else
        format.html { render action: "new" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wines/1
  # PUT /wines/1.json
  def update
    @winery = Winery.find(params[:winery_id])
    @wine = @winery.wines.find(params[:id])

    respond_to do |format|
      if @wine.update_attributes(params[:wine])
        format.html { redirect_to [@wine.winery, @wine] , notice: 'Wine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @winery = Winery.find(params[:winery_id])
    @wine = @winery.wines.find(params[:id])
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to winery_wines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wineapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', root_path %>
<br />
<%= yield %>

</body>
</html>

app/views/wineries/_form.html.erb
<%= form_for(@winery) do |f| %>
  <% if @winery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@winery.errors.count, "error") %> prohibited this winery from being saved:</h2>

      <ul>
      <% @winery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wineries/edit.html.erb
<%= link_to "Back to all wineries", wineries_path %> |
<%= link_to "Show #{@winery.name} details", @winery %>

<%= render 'form' %>

app/views/wineries/index.html.erb
<h1>Listing all wineries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wineries.each do |winery| %>
  <tr>
    <td><%= winery.name %></td>
    <td><%= winery.location %></td>
    <td><%= link_to 'Show', winery %></td>
    <td><%= link_to 'Edit', edit_winery_path(winery) %></td>
    <td><%= link_to 'Destroy', winery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<p>
<%= link_to 'New winery', new_winery_path %>
<br />
<%= link_to "List all wines", wines_path %>
</p>

app/views/wineries/new.html.erb
<h1>New winery</h1>

<%= render 'form' %>

<%= link_to 'Back', wineries_path %>

app/views/wineries/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back to all wineries', wineries_path %> |
<%= link_to "Edit #{@winery.name} details", edit_winery_path(@winery) %>
<p>
  <b>Name:</b>
  <%= @winery.name %>
</p>

<p>
  <b>Location:</b>
  <%= @winery.location %>
</p>

<p>
  <b>Types of wine:</b>
  <%= @winery.wines.count %>
</p>

<p>
<%= link_to "New #{@winery.name} wine", new_winery_wine_path(@winery) %>
<br />
<%= link_to "List #{@winery.name} wines",  winery_wines_path(@winery) %>
</p>

app/views/wines/_form.html.erb
<%= form_for([@wine.winery, @wine]) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wines/all.html.erb
<%= link_to 'Back to wineries', wineries_url %>
<h1>Listing all wines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Winery</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @wines.each do |wine| %>
  <tr>
    <td><%= wine.name %></td>
    <td><%= wine.winery.name %></td>
    <td><%= wine.description %></td>
    <td><%= link_to 'Show', [wine.winery, wine] %></td>
    <td><%= link_to 'Edit', edit_winery_wine_path(wine.winery, wine) %></td>
    <td><%= link_to 'Destroy', [wine.winery, wine], method: :delete, data: { confirm: "Are you sure? (Here be dragons...you'll get lost!)" } %></td>
  </tr>
<% end %>
</table>

app/views/wines/edit.html.erb
<%= link_to "Back to #{@wine.winery.name} wines", winery_wines_path(@wine.winery) %> |
<%= link_to "Show #{@wine.name} details", [@wine.winery, @wine] %>

<%= render 'form' %>

app/views/wines/index.html.erb
<%= link_to "Back to #{@winery.name} details", winery_path(@winery) %>
<h1> <%= @winery.name %> Wines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @wines.each do |wine| %>
  <tr>
    <td><%= wine.name %></td>
    <td><%= wine.description %></td>
    <td><%= link_to 'Show', [wine.winery, wine] %></td>
    <td><%= link_to 'Edit', edit_winery_wine_path(wine.winery, wine) %></td>
    <td><%= link_to 'Destroy', [wine.winery, wine], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "New #{@winery.name} wine", new_winery_wine_path %>

app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render 'form' %>

<%= link_to 'Back', winery_wines_path(@wine.winery) %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Back to #{@wine.winery.name} wines", winery_wines_path(@wine.winery) %> | <%= link_to "Edit #{@wine.name} details", edit_winery_wine_path(@wine.winery, @wine) %>
<p>
  <b>Name:</b>
  <%= @wine.name %>
</p>

<p>
  <b>Description:</b>
  <%= @wine.description %>
</p>